# Generated by Django 4.1.1 on 2022-10-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField()),
                ('date_departure', models.DateField()),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the category', max_length=256, unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image', null=True, upload_to='categories')),
                ('square', models.PositiveSmallIntegerField()),
                ('places', models.PositiveSmallIntegerField(default=1)),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('name',), 'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, null=True, unique=True, max_length=254)),
                ('full_name', models.CharField(max_length=256)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('citizenship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.citizenship')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tenants', to='booking.booking')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to='booking.client')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('thumbnail', models.ImageField(blank=True, help_text='Thumbnail image', null=True, upload_to='rooms')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='booking.category')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='booking.room'),
        ),
    ]
